name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean node_modules
        run: rm -rf node_modules

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npx playwright test --reporter=allure-playwright

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean

      - name: List allure-report directory
        run: ls -la allure-report

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Set up Git for GitHub Pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: npx gh-pages -d allure-report -r https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/ovlasova1705/AutomatedTests_API.git

      - name: Clean Allure Report folder
        run: npm run allure:clean:report

      - name: Build TypeScript files
        run: npm run build

      - name: Send detailed Telegram report on success
        if: success()
        run: |
          echo "✅ Tests passed successfully!" > success_message.txt
          node dist/send-telegram-report.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Send detailed Telegram report on failure
        if: failure()
        run: |
          echo "❌ Tests failed. Check the details in the Actions tab." > failure_message.txt
          node dist/send-telegram-report.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
